name: Build macOS App with jpackage

on:
  push:
    branches: [ "main" ]  # Cambia si tu rama principal se llama distinto
  pull_request:
    branches: [ "main" ]

jobs:
  build-macos:
    runs-on: macos-latest  # usa una VM con macOS

    steps:
      # 1. Clona tu repo
      - name: Check out
        uses: actions/checkout@v3

      # 2. Compila todo el .java en 'src' y pon los .class en 'out'
      - name: Compile Java
        run: |
          mkdir -p out
          javac -d out $(find src -name "*.java")

      # 3. Crea el .jar nombrándolo "MyApp.jar"
      #    Ajusta "com.tuempresa.Main" a la clase con el main que quieras usar
      - name: Create JAR
        run: |
          jar cfe Snake.jar com.Javier.SnakeGame -C out .

      # 4. Genera el instalador DMG con jpackage
      - name: Package with jpackage
        run: |
          mkdir -p dist
          jpackage \
            --type dmg \
            --name MyApp \
            --input . \
            --main-jar Snake.jar \
            --main-class com.Javier.SnakeGame \
            --dest dist

      # 5. Sube el .dmg como un artefacto descargable
      - name: Upload dmg artifact
        uses: actions/upload-artifact@v3
        with:
          name: Snake-dmg
          path: dist/*.dmg
